Added new address mapping to DRAMSim3
bespoke-silicon-group/basejump_stl pull request #331
Opened 2020-08-06 00:30 UTC by farzamgl

- Added the `rochrababgco` address mapping to the translation modules
- Fixed a small error in Verilog parameter validation vs DRAMSim3

2020-08-08 02:16 UTC, tommydcjung commented on bsg_test/bsg_nonsynth_dramsim3_map.v
> +        assign mem_addr_o[i] = 1'b0;
Can we just do "assign mem_addr_o = {ch_addr_i[], ch_addr_i[], ch_addr_i[], ...};" ?

2020-08-08 02:43 UTC, farzamgl commented on bsg_test/bsg_nonsynth_dramsim3_map.v
> +        assign mem_addr_o[i] = 1'b0;
Not really because SystemVerilog doesn't like signals with zero widths and some of the fields can be empty depending on the parameters.

2020-08-08 04:30 UTC, taylor-bsg commented on testing/bsg_test/dramsim3_bandwidth/testbench.v
> +`define dram_pkg bsg_dramsim3_lpddr3_8gb_x32_1600_pkg
Instead of flip-flopping back and forth by manually editing the file, does it make sense to just add two more tests and then include the common source file?

2020-08-08 04:46 UTC, farzamgl commented on testing/bsg_test/dramsim3_bandwidth/testbench.v
> +`define dram_pkg bsg_dramsim3_lpddr3_8gb_x32_1600_pkg
Oh, that's actually wrong. I forgot to revert that line back. That testbench is not for lpddr3.

2020-08-08 15:47 UTC, mrutt92 commented on testing/bsg_test/dramsim3_bandwidth/testbench.v
> +`define dram_pkg bsg_dramsim3_lpddr3_8gb_x32_1600_pkg
Or define it from the command line.

2020-08-08 21:06 UTC, dpetrisko commented on bsg_test/bsg_nonsynth_dramsim3_map.v
> +        assign mem_addr_o[i] = 1'b0;
Not necessarily suggesting it, but I recently discovered that you can use zero width signal in concatenations:

https://verificationacademy.com/forums/systemverilog/zero-bit-width-array

2020-08-08 21:26 UTC, farzamgl commented on bsg_test/bsg_nonsynth_dramsim3_map.v
> +        assign mem_addr_o[i] = 1'b0;
Yeah but you cannot address a zero width part of an array with [... +: 0]

2020-08-08 21:26 UTC, farzamgl commented on testing/bsg_test/dramsim3_bandwidth/testbench.v
> +`define dram_pkg bsg_dramsim3_lpddr3_8gb_x32_1600_pkg
The problem with that is that the python files that generate the trace are all hardcoded for HBM2.

2020-08-08 21:31 UTC, dpetrisko commented on bsg_test/bsg_nonsynth_dramsim3_map.v
> +        assign mem_addr_o[i] = 1'b0;
The idea would be to do something like this {actual_slice!=0{ch_addr_i[0+:BSG_MAX(1, actual_slice)}}

2020-08-08 22:14 UTC, farzamgl commented on bsg_test/bsg_nonsynth_dramsim3_map.v
> +        assign mem_addr_o[i] = 1'b0;
I see. Yeah, I think this way is a bit cleaner.

2020-08-10 21:02 UTC, farzamgl commented
Can we merge this, if there aren't any specific issues?

2020-08-10 21:04 UTC, drichmond commented
Has anyone run this PR in HammerBlade?

2020-10-15 01:13 UTC, drichmond commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
How do I replace this in HammerBlade?

2020-10-15 01:13 UTC, drichmond commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
@farzamgl

2020-10-15 02:02 UTC, farzamgl commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I see. I removed this struct because some of the fields can be empty(for example if there's only 1 rank), and we cannot have an empty signal in the struct.

2020-10-15 16:29 UTC, drichmond commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
Removing things isn't the intent of your PR, right? You only changed the address map?

2020-10-15 16:32 UTC, tommydcjung commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I think this would also work in replicant? https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/testbenches/common/v/spmd_testbench.v#L881

2020-10-15 16:33 UTC, farzamgl commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
It wasn't the intent, but during the address mapping changes I realized that we could have 0-bit wide signals in that struct(depending on the configuration), so I had to remove it.

2020-10-15 16:36 UTC, drichmond commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
> I think this would also work in replicant? https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/testbenches/common/v/spmd_testbench.v#L881

My initial (rapid) reaction is yes. Though I would like to remove the magic constants.

2020-10-15 18:21 UTC, farzamgl commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I think you can use the `dramsim3_*_width` macros for the struct definition in HB code.

2020-10-15 20:54 UTC, mrutt92 commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I made those macros for the convenience of designs that wanted to use the HBM simulation. They're not used in the design itself because they match DRAMSim3's address configuration, which is specified either in the C++ source or some config file. I didn't anticipate the empty field problem. Maybe the thing to do here is follow what @tommydcjung did in that spmd_testbench except define them in this header with some general name. Magic numbers are OK as long as they're defined in exactly one place, right? That way people who want to use this don't have to go rooting through our projects to find the address map they need.

2020-10-16 00:33 UTC, drichmond commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
@farzamgl do you need to remove this macro for the correctness of your code?

2020-10-16 00:38 UTC, dpetrisko commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I’m going to hop in without full context here and say this sounds like a problem which can be solved with unions

2020-10-16 01:13 UTC, farzamgl commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
> @farzamgl do you need to remove this macro for the correctness of your code?

My code doesn't use any structs for the address, but yes it was creating issues in its current form(in the testbench).

> I’m going to hop in without full context here and say this sounds like a problem which can be solved with unions

@dpetrisko Is there a way to define the struct with unions so it doesn't create 0-bit signal errors?

2020-10-16 01:57 UTC, tommydcjung commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I agree with @mrutt92 and I think we should just be agile and move on.

2020-10-16 01:58 UTC, tommydcjung approved these changes

2020-10-16 02:05 UTC, drichmond requested changes
We need to find a satisfactory solution, before moving on. Not all questions have been addressed.

2020-10-16 02:59 UTC, dpetrisko commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
```
typedef union packed
{
  struct packed
  {
     logic [`BSG_MAX(col_width_p, 1)-1:0] col;
     logic [`BSG_MAX(row_width_p, 1)-1:0] row;
   } addr_with_row_and_col;
  struct packed
  {
     logic [`BSG_MAX(row_width_p)-1:0] row;
  } addr_without_col;
} dram_addr
```

@farzamgl  something like this?

2020-10-16 17:56 UTC, farzamgl commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
I don't this is practical. There's going to be 16 possible combinations in the union.
I think generating the struct in your own testbench is a cleaner way of doing it.

2020-10-16 17:57 UTC, dpetrisko commented on bsg_test/bsg_dramsim3_pkg.v
> -`define declare_dramsim3_ch_addr_s_with_pkg(typename_mp, dram_pkg) \
The struct definitions exists either way

2020-10-16 18:33 UTC, tommydcjung commented on bsg_test/bsg_dramsim3_pkg.v
> +package bsg_dramsim3_lpddr3_8gb_x32_1600_pkg;
How about inside each package define the address mapping struct? I'm against the union idea, because like @farzamgl said, it's not a practical solution..

2020-10-16 18:51 UTC, mrutt92 commented on bsg_test/bsg_dramsim3_pkg.v
> +package bsg_dramsim3_lpddr3_8gb_x32_1600_pkg;
Union's seem like a good thing to use if you're trying to share structs on the same logic, which is not the case here. Defining a struct for each package seems more like what we want.

2020-10-16 19:02 UTC, farzamgl commented on bsg_test/bsg_dramsim3_pkg.v
> +package bsg_dramsim3_lpddr3_8gb_x32_1600_pkg;
This is a better solution imo, but you have to change the code in HB.

2020-10-16 19:21 UTC, mrutt92 commented on bsg_test/bsg_dramsim3_pkg.v
> +package bsg_dramsim3_lpddr3_8gb_x32_1600_pkg;
Stuff happens.

2020-10-16 19:22 UTC, mrutt92 commented on bsg_test/bsg_dramsim3_pkg.v
> +package bsg_dramsim3_lpddr3_8gb_x32_1600_pkg;
It's why version control exists :-)

2020-10-16 20:19 UTC, tommydcjung commented on bsg_test/bsg_dramsim3_pkg.v
> +package bsg_dramsim3_lpddr3_8gb_x32_1600_pkg;
Yeah we can update the HB to use this better solution. Not a big deal.

2020-10-16 22:22 UTC, drichmond approved these changes
To make my position extremely clear: BaseJump should evolve separately from HB, and HB is responsible for adapting.

That being said - we have a limited amount person-hours (we're all working on new features, deadlines, etc), so if there is a way to avoid introducing cascading changes they should be discussed. The excellent discussion has proven this isn't possible, but it seems like a good compromise has been found.

The irony is that we've all spent more time discussing this bug -- and in that time we collectively could have implemented and tested a fix in HB.

The current solution looks good, and thanks to @farzamgl for helping me get it into HB.

2020-10-17 17:15 UTC, merged