Fix #335
bespoke-silicon-group/basejump_stl pull request #336
Opened 2020-09-10 02:34 UTC by Xusine1131

Just by writing a simple script and fixing the minor exceptions manually.

2020-09-10 09:25 UTC, dpetrisko requested changes

2020-09-10 09:25 UTC, dpetrisko commented on bsg_clk_gen/bsg_clk_gen_osc.v
> +`include "bsg_defines.v"
could you undo the full file rewrite (line endings) here?

2020-09-10 09:25 UTC, dpetrisko commented on bsg_dataflow/bsg_fifo_1r1w_small_hardened.v
> +//
same here

2020-09-10 09:25 UTC, dpetrisko commented on bsg_math/bsg_hypotenuse/bsg_hypotenuse.v
> +// Hypotenuse
Same here

2020-09-10 09:25 UTC, dpetrisko commented on bsg_mesosync_io/tests/mesosynctb.v
> +// This testbench goes through different steps of initializing
same here

2020-09-10 09:25 UTC, dpetrisko commented on bsg_mesosync_io/tests/mesosynctb_gate_level.v
> +// This testbench goes through different steps of initializing
same here

2020-09-10 09:25 UTC, dpetrisko commented on bsg_misc/bsg_clkgate_optional.v
> +// MBT: This module has a broken interface because it uses bypass_i as a live input, which could use glitching
same here

2020-09-10 09:25 UTC, dpetrisko commented on bsg_noc/bsg_mesh_to_ring_stitch.v
>  // AUTOGENERATED FILE; DO NOT MODIFY.
need to modify the python file as well

2020-09-10 13:03 UTC, Xusine1131 commented on bsg_clk_gen/bsg_clk_gen_osc.v
> +`include "bsg_defines.v"
In fact, I don't know why git recognizes it as a full file change since almost all files are modified automatically by exactly the same script...

2020-09-11 17:34 UTC, taylor-bsg commented
Looks like some great changes -- if you can fix this white space issue with those few files, I think we should be good to go to merge it!

M

2020-09-26 06:36 UTC, taylor-bsg approved these changes
Looks good. Takeaway: telling the tools to pre-include saves ~600 lines across 350 files, but most users are not sophisticated enough to know about pre including files. There is a minor nuance about whether we should include bsg_defines in files that do not currently use the macros, but it seems okay to standardize on saying it is okay to blanket include it just so you don't have to worry about whether you need it or not.

2020-09-26 06:38 UTC, merged