Refactoring bsg_mem_1rw_sync_xxx_subbanked modules
bespoke-silicon-group/basejump_stl pull request #603
Opened 2022-10-23 21:53 UTC by KinzaQamar

This PR refactors the modules by 

1. Renaming bsg_mem_1rw_sync_xxx_subbanked to bsg_mem_1rw_sync_xxx_segmented
2. When num_subbanks_p is 1, the dffs of backing SRAM will latch the reads.

2022-10-30 19:20 UTC, KinzaQamar commented
@dpetrisko does this looks good to you?

2022-10-30 22:31 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_mask_write_bit_segmented.v
> +      if (latch_last_read_p) begin: llr
how about if (latch_last_read_p && num_subbank_p > 1) and get rid of the above clause?

2022-10-30 22:32 UTC, dpetrisko requested changes
Thanks for the ping! Minor refactor requested

2022-11-04 20:51 UTC, KinzaQamar commented
@dpetrisko, changes have been made!

2022-11-25 07:44 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_segmented.v
> +        ,.latch_last_read_p(latch_last_read_p == num_subbank_p)
let's do latch_last_read_p && num_subbank_p == 1 to be very explicit here

2022-11-25 07:44 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_segmented.v
> +
Remove comment; I think this is from a future enhancement

2022-11-25 07:44 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_mask_write_byte_segmented.v
> +      ,.latch_last_read_p(latch_last_read_p == num_subbank_p)
let's do latch_last_read_p && num_subbank_p == 1 to be very explicit here

2022-11-25 07:45 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_mask_write_bit_segmented.v
> +      ,.latch_last_read_p(latch_last_read_p == num_subbank_p)
let's do latch_last_read_p && num_subbank_p == 1 to be very explicit here

2022-11-25 07:45 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_mask_write_bit_segmented.v
> + *  This module behaves like an N bsg_mem_1rw_sync_mask_write_bit
Remove comment; I think this is from a future enhancement

2022-11-25 07:45 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_mask_write_byte_segmented.v
> + *  This module behaves like an N bsg_mem_1rw_sync_mask_write_byte
Remove comment; I think this is from a future enhancement

2022-11-25 07:46 UTC, dpetrisko requested changes
Hi, sorry for the delay. Very minor change requested then LGTM

2022-12-12 22:30 UTC, dpetrisko commented
Hi @KinzaQamar, really minor last thing before merging. Can you change num_subbanks_p to num_segments_p?

2022-12-14 15:15 UTC, KinzaQamar commented
> Hi @KinzaQamar, really minor last thing before merging. Can you change num_subbanks_p to num_segments_p?

2022-12-14 20:42 UTC, dpetrisko commented
Awesome thanks!

2022-12-14 20:42 UTC, dpetrisko approved these changes

2022-12-14 20:43 UTC, merged