Updates testbenches for bsg_dataflow
bespoke-silicon-group/basejump_stl pull request #611
Opened 2022-11-22 06:17 UTC by BrendenPage

Refactored testbench infrastructure update from https://github.com/bespoke-silicon-group/basejump_stl/pull/610

## Summary

Fixes testbenches and makefiles (allows them to compile and run) for all existing dataflow tests.

Adds `bsg_dataflow` level makefile to run all make commands in directory (for easy syntax verification and directory-level clean commands)

## Issue Fixed

Previous infrastructure had not been updated in a number of years, leading to issues regarding compilation from updated module port lists and outdated tooling/non-automated tooling setup in Makefiles

## Verification

I have verified that all testbenches are properly run via using `make` on each subdirectory in `testing/bsg_dataflow`

`bsg_fifo_1r1w_large` and `bsg_fifo_1r1w_large` do not properly finish as they have log file errors I do not understand but the tests themselves run and pass

`bsg_parallel_in_serial_out_passthrough_arb` and `bsg_channel_tunnel` fail for reasons unknown but most likely for reasons outside the scope of this PR.

2022-11-25 07:42 UTC, dpetrisko requested changes
Very nice! Some minor feedback to address

2022-11-25 07:42 UTC, dpetrisko commented on testing/Makefile.sim
> +export BSG_CADENV_DIR = $(abspath .)/../../../../bsg_cadenv
A little more flexible:

```
TOP ?= $(shell git rev-parse --show-toplevel)
BSG_CADENV_DIR ?= $(TOP)/../bsg_cadenv
```

No need for export

2022-11-25 07:42 UTC, dpetrisko commented on testing/bsg_dataflow/bsg_channel_narrow/test_bsg.v
> +  parameter reset_cycles_lo_p=0,
The reset low cycles are important here; this is helping to test X-pessimism after coming out of reset

2022-11-25 07:42 UTC, dpetrisko commented on testing/bsg_dataflow/bsg_compare_and_swap/test_bsg.v
> +  parameter reset_cycles_lo_p=0,
See above

2022-11-25 07:42 UTC, dpetrisko commented on testing/bsg_dataflow/bsg_fifo_1r1w_large/Makefile
> +export BSG_CADENV_DIR = $(abspath .)/../../../../bsg_cadenv
A little more flexible:

TOP ?= $(shell git rev-parse --show-toplevel)
BSG_CADENV_DIR ?= $(TOP)/../bsg_cadenv


No need for export

2022-11-25 07:42 UTC, dpetrisko commented on testing/bsg_dataflow/bsg_fifo_bypass/Makefile
> +export BSG_CADENV_DIR = $(abspath .)/../../../../bsg_cadenv
A little more flexible:

TOP ?= $(shell git rev-parse --show-toplevel)
BSG_CADENV_DIR ?= $(TOP)/../bsg_cadenv


No need for export

2022-12-20 08:21 UTC, dpetrisko commented
Is this ready to review again?

2022-12-20 19:26 UTC, BrendenPage commented
> Is this ready to review again?

Yes! It should be ready to go.

2022-12-20 19:39 UTC, dpetrisko commented on testing/bsg_dataflow/Makefile
> +	$(foreach x,$(TEST_DIRS), cd $(x) && make && cd ../;)
nit; 
$(MAKE) -C $(x)
will preserve -j and other options when passing into the subshell (and prevent the need for a cd)

2023-01-17 22:07 UTC, dpetrisko commented
LGTM, merging

2023-01-17 22:08 UTC, merged