Clock Mux macro for Ultrascale
bespoke-silicon-group/basejump_stl pull request #615
Opened 2022-12-07 13:16 UTC by mysoreanoop

Tested with 2/3/4:1 muxes with balanced_p and harden_p -- each synthesizes, FPGA-simulates.

2022-12-08 21:01 UTC, dpetrisko commented on hard/ultrascale_plus/bsg_misc/bsg_mux.v
> +      if(els_p == 2)
let's get rid of the first clause and just do

if (harden_p && balanced_p && els_p == 2)
  begin : macro
else if (harden_p && balanced_p && els_p == 3)
  begin : macro
else if (harden_p && balanced_p && els_p == 4)
  begin : macro
else
  begin : notmacro

2022-12-08 21:02 UTC, dpetrisko commented on hard/ultrascale_plus/bsg_misc/bsg_mux.v
> +module bsg_macro_clk_mux_2_1
let's make this an actual `define to avoid introducing more hierarchy. Some synthesis tools unavoidably insert buffers for feedthroughs

2022-12-08 21:02 UTC, dpetrisko requested changes
Looks good! minor changes requested

2022-12-09 10:29 UTC, mysoreanoop commented on hard/ultrascale_plus/bsg_misc/bsg_mux.v
> +module bsg_macro_clk_mux_2_1
Do you mean something like https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_async/bsg_sync_sync.v ?
Would that avoid the feedthrough buffers? We would still elaborate the macro and instantiate the module within, right?

2022-12-12 22:27 UTC, dpetrisko commented
LGTM!

2022-12-12 22:28 UTC, dpetrisko approved these changes

2022-12-12 22:28 UTC, merged