Clock gate hard macro for Xilinx Ultrascale
bespoke-silicon-group/basejump_stl pull request #628
Opened 2022-12-20 19:25 UTC by mysoreanoop

+ fixes for bsg_mux (argument reordering)

2022-12-20 19:34 UTC, dpetrisko commented on hard/ultrascale_plus/bsg_misc/bsg_clkgate_optional.v
> +`ifndef SYNTHESIS
I would only put the BUFGCE option (no if-else). The other will always be broken in FPGA synthesis

2023-01-05 08:42 UTC, mysoreanoop commented
Requesting review

2023-01-05 08:57 UTC, dpetrisko requested changes
Looks good with small fix

2023-01-05 08:57 UTC, dpetrisko commented on hard/ultrascale_plus/bsg_misc/bsg_clkgate_optional.v
> +    #( parameter is_ce_inverted = 1'b0
Let's leave out these parameters since they don't exist in the "synth" bsg_clk_gate_optional

2023-01-05 09:18 UTC, mysoreanoop commented on hard/ultrascale_plus/bsg_misc/bsg_clkgate_optional.v
> +    #( parameter is_ce_inverted = 1'b0
Updated

2023-01-05 23:48 UTC, dpetrisko approved these changes
LGTM!

2023-01-05 23:48 UTC, merged