Updated bsg_cache parametrization for single sets
bespoke-silicon-group/basejump_stl pull request #656
Opened 2023-05-28 20:01 UTC by RobertCrist

Fixed the parametrization of bsg_cache so that it can run with a single set

2023-05-29 10:21 UTC, dpetrisko commented on bsg_cache/bsg_cache_miss.v
> +            addr_index_v,
Use zero-width concatenation to clean up these if statements.

{(sets_p>1){addr_index_v}

The line below is an example of this:
{(block_size_in_words_p > 1){addr_block_offset_v}},

If the addr_block_offset_v is relevant, it will be included. Else, the expression will be ignored 0{addr_block_offset_v}.

Go throughout the code and find as many of these instances as you can

2023-05-29 10:21 UTC, dpetrisko commented on testing/bsg_cache/regression_64/Makefile
> -include ../../../../bsg_cadenv/cadenv.mk
Revert this makefile and the testbench -- too environment-specific

2023-05-29 10:22 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +      // tag_mem_addr_li = recover_lo
This seems suspicious -- did you also run regression for sets > 1?

2023-05-29 10:24 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +  // Hardcoding tag mem address if single set
Don't change the structure of the code significantly -- keep in the FSM and just modify addr_index and miss_tag_mem_addr appropriately

2023-05-29 10:27 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +  // Hardcoding tag mem address if single set
Also applies to stat mem change

2023-05-30 17:54 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +      = cache_pkt.addr[block_offset_width_lp+lg_sets_lp+:lg_ways_lp];
To avoid ifs, let's define

localparam way_offset_width_lp = sets_p > 1 ? block_offset_width_lp+lg_sets_lp : block_offset_width_lp

2023-05-30 17:55 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +      // stat_mem_addr_li = addr_index_v;
make sure to remove commented blocks

2023-06-01 06:10 UTC, RobertCrist commented on testing/bsg_cache/regression_64/Makefile
I am not sure why it says there is a difference here. Same with the testbench. There should be no changes.

2023-06-23 16:04 UTC, dpetrisko commented on bsg_cache/bsg_cache_miss.v
> +        dma_cmd_o = e_dma_send_fill_addr;
revert space

2023-06-23 16:05 UTC, dpetrisko commented on bsg_mem/bsg_mem_1r1w_sync_synth.v
> +         mem['0] <= w_data_i;
w_addr_li, like above

2023-06-23 16:05 UTC, dpetrisko commented on bsg_mem/bsg_mem_1rw_sync_mask_write_bit.v
> +   if (els_p > 1) begin
Add to assert conditional instead

2023-06-23 16:07 UTC, dpetrisko commented on testing/bsg_cache/regression_64/Makefile
says whitespace only changes, you can revert by doing 

git checkout master -- testing/bsg_cache/regression_64/Makefile
git checkout master -- testing/bsg_cache/regression_64/testbench.v

2023-06-23 16:09 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +    assign sbuf_data_mem_addr = sbuf_entry_lo.addr[lg_data_mask_width_lp+:lg_block_size_in_words_lp+((sets_p>1)?lg_sets_lp:0)];
+:lg_data_mem_els_lp should work

2023-06-23 16:18 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +    assign sbuf_data_mem_addr = sbuf_entry_lo.addr[lg_data_mask_width_lp+:lg_block_size_in_words_lp+((sets_p>1)?lg_sets_lp:0)];
think +:lg_data_mem_els_lp is sufficient

2023-06-26 19:37 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +    // assign sbuf_data_mem_addr = sbuf_entry_lo.addr[lg_data_mask_width_lp+:lg_block_size_in_words_lp+((sets_p>1)?lg_sets_lp:0)];
delete comment

2023-06-26 19:39 UTC, dpetrisko commented
LGTM after extraneous comment is deleted

2023-07-11 16:25 UTC, dpetrisko requested changes

2023-07-11 16:25 UTC, dpetrisko commented on bsg_cache/bsg_cache.v
> +    assign sbuf_data_mem_addr = sbuf_entry_lo.addr[lg_data_mask_width_lp+:lg_block_size_in_words_lp];
This seems off, should be way_offset_width?

2023-07-13 20:13 UTC, tommydcjung commented on bsg_cache/bsg_cache.v
> +  localparam sbuf_data_mem_els_lp=(sets_p == 1) ? lg_block_size_in_words_lp : lg_block_size_in_words_lp+lg_sets_lp;
I would rename this to sbuf_data_mem_addr_offset_lp.
Shouldn't it be using lg_burst_len_lp instead of lg_block_size_in_words_lp?

2023-07-14 18:18 UTC, RobertCrist commented on bsg_cache/bsg_cache.v
> +  localparam sbuf_data_mem_els_lp=(sets_p == 1) ? lg_block_size_in_words_lp : lg_block_size_in_words_lp+lg_sets_lp;
This parameter was made for when [(burst_len_lp == block_size_in_words_p)](https://github.com/bespoke-silicon-group/basejump_stl/blob/aecd3a5c5db690fea6037606ab6d0d1928eb433c/bsg_cache/bsg_cache.v#L644C1-L645C113) but this comment made me realize that I forgot the [else case](https://github.com/bespoke-silicon-group/basejump_stl/blob/aecd3a5c5db690fea6037606ab6d0d1928eb433c/bsg_cache/bsg_cache.v#L647-L648). I combined both cases into one line but it is pretty long so let me know if you have a better idea to split it up.

2023-07-17 16:42 UTC, tommydcjung commented on bsg_cache/bsg_cache.v
> +  localparam sbuf_data_mem_els_lp=(sets_p == 1) ? lg_block_size_in_words_lp : lg_block_size_in_words_lp+lg_sets_lp;
I think  using $clog2(sets_p) instead of lg_sets_lp will simplify

2023-07-19 07:30 UTC, RobertCrist commented on bsg_cache/bsg_cache.v
> +  localparam sbuf_data_mem_els_lp=(sets_p == 1) ? lg_block_size_in_words_lp : lg_block_size_in_words_lp+lg_sets_lp;
I like that! Should be added now

2023-07-20 20:38 UTC, dpetrisko approved these changes

2023-07-20 23:36 UTC, tommydcjung commented
If sets_p=1, shouldn't the addr_i of tag_mem be tied to 1'b0? I think if you read with addr_i=1'b1, the output of bsg_mem will be X.

2023-07-20 23:58 UTC, dpetrisko commented
Hi Tommy #660 takes care of that

2023-07-21 16:43 UTC, tommydcjung commented
okay nice. did you run the regression with sets_p=1?

2023-07-21 18:45 UTC, RobertCrist commented
> 

Hello Tommy, yes, it has been tested in the following configurations:
sets = 1
ways = 8
--------------
sets = 64
sets = 8

I double checked this morning just to be safe!

2023-07-21 18:46 UTC, RobertCrist commented
Hello Tommy, yes, it has been tested in the following configurations:
sets = 1
ways = 8
--------------
sets = 64
sets = 8

I double-checked this morning just to be safe!

2023-07-21 18:48 UTC, RobertCrist commented
> okay nice. did you run the regression with sets_p=1?

Hello Tommy, yes, it has been tested in the following configurations:
sets = 1
ways = 8

sets = 64
sets = 8

I double-checked this morning just to be safe!

2023-07-21 18:57 UTC, tommydcjung approved these changes

2023-07-22 16:51 UTC, merged